language: node_js

node_js:
  - "node"
  - "8"

script:
  - npm run production
  - ls $TRAVIS_BUILD_DIR

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: "dist"
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
